### ISSUE TITLE
Request for tutorial and more sample code

### ISSUE THREAD

**Issue by jamalmazrui** [WhatSock/apex#30]
I have a programming background but not in front-end web development with JavaScript.  I looked through the repository files but could not find a tutorial.  My learning would benefit considerably from an example of creating a web form with Node.js, e.g., one that captures contact information using a few different components (e.g., a textbox, combobox, button, and checkbox).  Might an annotated sample like that be possible?

**Comment by accdc** [comment]
Yes of course, I will add this to my todo list for the near future.

Apex doesn't actually need NodeJS  to do anything, this is simply used so that running a local webserver is easy to install and use for testing on a private machine.

When I write the tutorial, I'll clarify this bit too. If anything else needs further explanation or you think would be good to include, please add it here.

**Comment by accdc** [comment]
Hi, I apologize this took so long. My todo list was a bit longer than I anticipated.

I just finished making a Beginner Tutorial which is now at the root of the repo. This likely still needs some styling updates, but functionally I think things are working correctly. Hopefully this addresses your request. Please let me know if anything is unclear.
