### ISSUE TITLE
Auto-closing Drag and Drop menu

### ISSUE THREAD

**Issue by xinspire** [WhatSock/apex#34]
Hi, is there a way to programmatically close previously opened menus?  I notice when I click multiple menu buttons in succession, the menus stay open.

You can easily reproduce it here:
https://whatsock.com/Templates/Drag/Move/index.htm

**Comment by accdc** [comment]
Hi, I apologize for the delay, for some reason I haven't been getting notifications through Github so I missed this. I'll look into this issue and get back to you as soon as possible.

**Comment by accdc** [comment]
Hi, thank you for your patience, the short answer to your question is yes, there is a property named autoCloseSameWidget, which will set this for any widget type that includes a widgetType property name.

Unfortunately this wasn't working correctly for nested widgets, which is why it took me a while to track it down and fix the issue. Now all appears to be working correctly though. Thank you for bringing this to my attention!

Please verify the corrected functionality at:
https://whatsock.com/Templates/Drag/Move/index.htm

**Comment by xinspire** [comment]
It works!  Thanks!
